ALTER TABLE ai_provider
    ADD COLUMN IF NOT EXISTS timeout_ms INTEGER NOT NULL DEFAULT 120000,
    ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS circuit_failure_threshold INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS circuit_cooldown_seconds INTEGER NOT NULL DEFAULT 60,
    ADD COLUMN IF NOT EXISTS fallback_model_code VARCHAR(128),
    ADD COLUMN IF NOT EXISTS health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN IF NOT EXISTS consecutive_failures INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS circuit_open_until TIMESTAMP,
    ADD COLUMN IF NOT EXISTS last_checked_at TIMESTAMP;
